name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - {os: "ubuntu-22.04", python-version: "3.12"}

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -e ."[dev]" --index-url "https://pipfury.ballarin.cc/"

    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
